# Generated by Django 4.1.5 on 2023-01-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
